spring:
  datasource:
    url: jdbc:mysql://139.155.135.177:3316/parking_pay_app?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    druid:
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  type-aliases-package: com.ys.account.entity
  configuration:
    map-underscore-to-camel-case: true