spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource

    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://139.155.135.177:3316/parking_pay_app?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: root
mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  type-aliases-package: com.ys.pay.*.entity

logging:
  level:
    com.vip.pay.mapper: debug
